# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20170613_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
