# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 23:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20170613_2227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('votes', django.db.models.manager.Manager()),
            ],
        ),
    ]
